runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: .*  # This regex directs all routes to main.app
  script: main.app

libraries:
- name: MySQLdb
  version: "latest"

env_variables:
  CLOUDSQL_CONNECTION_NAME: duke-information-bot:us-east1:myinstance
  CLOUDSQL_USER: root@localhost
  CLOUDSQL_PASSWORD: HackDuke2016!
